<a href="https://colab.research.google.com/github/ssmartin-code/MVMC/blob/main/2_ProcesamientoDatosRecibidos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Agrupar por APN o Titular

Una vez recibido del servicio de montes la consulta catastral se debe hacer una copia en el siguiente  f"/content/drive/MyDrive/Catastro/{monte}/2.Resultados Consulta Catastral Masiva/RC_{monte}.xlsx"

In [18]:
#Instalar Librerias
!pip install pandas
!pip install openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [19]:
#Importar Librerias
import pandas as pd

In [21]:
# Variables
monte = "Bullaso"

In [22]:
# Rutas de archivos
directorio = f"/content/drive/MyDrive/Catastro/{monte}/2.Resultados Consulta Catastral Masiva/RC_{monte}.xlsx"

In [23]:
# Leer el archivo Excel y obtener los nombres de las columnas
datos = pd.read_excel(directorio)
nombres_encabezados = datos.columns.tolist()

# Filtrar los nombres que comienzan por "NIF"
var_NIF = [encabezado for encabezado in nombres_encabezados if encabezado.startswith("NIF")]

# Solo tomar la segunda columna de la lista var_NIF
if len(var_NIF) > 1:
    var_NIF = [var_NIF[1]]
print(var_NIF)

# Filtrar los nombres que corresponden a las columnas a mostrar
columnas_mostrar = ['RC', 'SUF', 'APN', 'DFT1', 'DFT2'] + var_NIF

# Filtrar las filas donde la columna 'APN' no es nula
datos_filtrados = datos[columnas_mostrar].dropna(subset=['APN'])

# Agrupar por 'APN' y obtener una lista de 'RC' asociados a cada 'APN'
Info_Titulares = datos_filtrados.groupby('APN').agg({
    'RC': lambda x: ', '.join(sorted(set(x))),  # Combine unique 'RC' values into a comma-separated string
    'SUF': 'first',   # Take the first 'SUF' value for each 'APN'
    'DFT1': 'first',  # Take the first 'DFT1' value for each 'APN'
    'DFT2': 'first',  # Take the first 'DFT2' value for each 'APN'
    **{col: 'first' for col in var_NIF},  # Take the first value for each NIF column
}).reset_index()

# Mostrar el resultado
display(Info_Titulares)

# Group by y summarize en group_by_RF_2
group_by_RF_2 = datos[['RC', 'APN']].dropna(subset=['APN']).groupby('RC').agg({'APN': lambda x: ', '.join(pd.unique(x))}).reset_index()
UnaRCVariostitulares = group_by_RF_2.rename(columns={'APN': 'APNs'})
display(UnaRCVariostitulares)

# Guardado en archivos Excel
Guardar_excel_Info_Titulares = f"/content/drive/MyDrive/Catastro/{monte}/4.Filtrado datos/Filtrado_{monte}_Info_Titulares_colab.xlsx"
Info_Titulares.to_excel(Guardar_excel_Info_Titulares, index=True)

Guardar_excel_UnaRCVariostitulares = f"/content/drive/MyDrive/Catastro/{monte}/4.Filtrado datos/Filtrado_{monte}_UnaRCVariostitulares_colap.xlsx"
UnaRCVariostitulares.to_excel(Guardar_excel_UnaRCVariostitulares, index= False)

# Guardado en archivos CSV
Guardar_csv_Info_Titulares = f"/content/drive/MyDrive/Catastro/{monte}/4.Filtrado datos/Filtrado_{monte}_Info_Titulares_colab.csv"
Info_Titulares.to_csv(Guardar_csv_Info_Titulares, index=False)

Guardar_csv_UnaRCVariostitulares = f"/content/drive/MyDrive/Catastro/{monte}/4.Filtrado datos/Filtrado_{monte}_UnaRCVariostitulares_colap.csv"
UnaRCVariostitulares.to_csv(Guardar_csv_UnaRCVariostitulares, index=False)

['NIF12']

,APN,RC,SUF,DFT1,DFT2,NIF12
0,ALBA FERNANDEZ JOSE M,33029A02900234,None,PQ ILLANO,33734 ILLANO (ASTURIAS),None
1,ALBA FERNANDEZ JOSE MARIA,33029A02900237,HEREDEROS DE,LG VILLAR BULLASO,33734 ILLANO (ASTURIAS),11299979X
2,ALVAREZ CANCIO JOSE MANUEL,"33029A02900582, 33029A02900595, 33029A02900630...",HEREDEROS DE,LG LANTERO,33731 ILLANO (ASTURIAS),71851895X
3,ALVAREZ CASTRILLON JOSE ORENCIO,"33029A02900228, 33029A02900248, 33029A02900264...",HEREDEROS DE,LG VILLAR DE BULLASO,33731 ILLANO (ASTURIAS),11299951M
4,ALVAREZ FERNANDEZ BRUNO,33029A02900386,None,LG LLOMBATIN,33732 ILLANO (ASTURIAS),53520901Q
...,...,...,...,...,...,...
85,SANZO FERNANDEZ NILDA,33029A02900614,None,LG SOTO ARRIBA 16,33119 OVIEDO (ASTURIAS),71862827V
86,SUAREZ SIERRA ELVIRA,"33029A02900330, 33029A02900331",HEREDEROS DE,CL RAMON Y CAJAL 3 Pl:06 Pt:DR,33400 AVILES (AVILES) (ASTURIAS),10612188B
87,VALERO CLEMENTE MARIA DEL CARMEN,"33029A02900444, 33029A02900563, 33029A02900626...",None,CL PINTOR ANTONIO SAURA 3 Pl:05 Pt:B,28050 MADRID (MADRID),00275252B
88,VALLEDOR GARCIA JAVIER,"33029A02900258, 33029A02900260, 33029A02900288...",None,LG VILLAR DE BULLASO VILLAR DE BULLASO,33731 ILLANO (ASTURIAS),45425745D
89,VAZQUEZ SUAREZ LUIS,"33029A02900230, 33029A02900231, 33029A02900250...",HEREDEROS DE,LG VILLAR,33734 ILLANO (ASTURIAS),71834929H

                 RC                                               APNs
0    33029A02900225                          ALVAREZ MARTINEZ EDELMIRA
1    33029A02900226                             FERREIRA RANCAÑO MARIA
2    33029A02900227  MESA GONZALEZ JOSE, MESA GONZALEZ GONZALO, MES...
3    33029A02900228                    ALVAREZ CASTRILLON JOSE ORENCIO
4    33029A02900229                        FERNANDEZ MAGADAN FELICIDAD
..              ...                                                ...
464  33029A02900700                           CASTAEDO LOPEZ SECUNDINO
465  33029A02900701                            GARCIA HERIAS PRIMITIVO
466  33077A00100112  BRAÑA DEL ZAPURREL SL, MENDEZ FERNANDEZ MOISES...
467  33077A00100117                             PRINCIPADO DE ASTURIAS
468  33077A00109017                                DETALLE TOPOGRAFICO

[469 rows x 2 columns]

## Categorizar Tipo de propiedad

Ahora se puede categorizar el tipo de propiedad en "Privada", " Publica" "Desconocida".Utiliza UnaRC asociada a varios titulares para obtener el tipo de propiedad.

In [24]:
import pandas as pd
import os

# Directory for Excel and CSV files
excel_file_path  = f"/content/drive/MyDrive/Catastro/{monte}/4.Filtrado datos/Filtrado_{monte}_UnaRCVariostitulares_colap.xlsx"

# Words dictionary
words_dict = {"VECINOS", "VECINAL", "CONFEDERACION", "CAMINOS", "AYUNTAMIENTO","JUNTA","DESCUENTO","PRINCIPADO DE ASTURIAS","COMUNAL","FERROVIARIAS","DEMARCACION DE CARRETERAS","DEMARCACION DE COSTAS"}

# Read the Excel file
Excel_UnifRC_colap = pd.read_excel(excel_file_path)

# Function to map APNs to Tipo_Propiedad
def map_tipo_propiedad(apn_value):
    if apn_value == "EN INVESTIGACION":
        return "DESCONOCIDO"
    elif any(word.lower() in apn_value.lower() for word in words_dict):
        return "PÚBLICA"
    else:
        return "PRIVADA"

# Create the new "Tipo_Propiedad" column based on the mapping function
Excel_UnifRC_colap["Tipo_Propiedad"] = Excel_UnifRC_colap["APNs"].map(map_tipo_propiedad)


# Directory for Excel and CSV files
output_directory = f"/content/drive/MyDrive/Catastro/{monte}/5.Union_GIS"
output_directory_Excel = os.path.join(output_directory, f"Filtrado_{monte}_UnaRCVariostitulares_TP_colab.xlsx")
output_directory_CSV = os.path.join(output_directory, f"Filtrado_{monte}_UnaRCVariostitulares_TP_colab.csv")

# Save the DataFrame to Excel and CSV files
Excel_UnifRC_colap.to_excel(output_directory_Excel, index= False)
Excel_UnifRC_colap.to_csv(output_directory_CSV, index=False,encoding='utf-8 sig')